schema: xgc2.product.v1
id: xgc2-gazebo-sim-fs150-sitl
name: XGC2 FS150 SITL
version: 1.0.7-1
kind: ros1-apt
summary: FS150 PX4 1.12 iris SITL wrapper for Gazebo Classic.

ros:
  distro: noetic
  packages:
    - gazebo_sim_fs150_sitl

apt:
  distribution: focal
  install:
    - ros-noetic-xgc2-gazebo-sim-fs150-sitl
  packages:
    - ros-noetic-xgc2-gazebo-sim-fs150-sitl
  depends:
    - python3
    - ros-noetic-roslaunch
    - ros-noetic-mavros
    - ros-noetic-xgc2-gazebo-sim-px4-1-12

usage:
  install: |
    sudo apt update
    sudo apt install ros-noetic-xgc2-gazebo-sim-fs150-sitl
  smoke_test: |
    roslaunch --files gazebo_sim_fs150_sitl fs150.launch gui:=false

ownership:
  paths:
    - /opt/ros/noetic/share/gazebo_sim_fs150_sitl
    - /opt/ros/noetic/lib/gazebo_sim_fs150_sitl
